stages:
 - build
 - test
 - deploy

gradle-build:
  image: gradle:4.7-jdk8
  stage: build
  script:
    - gradle clean build
  artifacts:
    when: always
    paths:
      - build/libs/*.jar
      - build/reports/tests/test

pages:
  when: always
  stage: deploy
  dependencies:
    - gradle-build
  script:
    - mkdir public
    - mv build/reports/tests/test/* public/
  artifacts:
    when: always
    paths:
      - public

heroku-deploy:
  image: docker
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - docker build --build-arg JAR_FILE=build/libs/crypto-0.1.0-SNAPSHOT.jar --tag registry.heroku.com/crypto-to-smi/web .
    - docker login --username=kurczukmarcin@gmail.com --password=$HEROKU_API_KEY registry.heroku.com
    - docker push registry.heroku.com/crypto-to-smi/web
    - heroku container:release web
